### ISSUE TITLE
Failing to register admin account on new docker install

### ISSUE THREAD

**Issue by albertoventurini** [friendica/friendica#14815]
Hi everyone,

I am trying to install Friendica on my VPS with docker compose. I have an issue when I try to register the first (admin) user: when I fill out the form to register the user, the email is not sent.

This might be similar to https://github.com/friendica/friendica/issues/14767, so please let me know if I should rather add a comment there.

Here are a few more details about my issue.
- I'd rather not set up a local SMTP server. I have a Fastmail account, so I'd like to use their server. I generated an API key, but from Fastmail's side, the key appears as never used - as if Friendica never attempted to send the email.
- I guess I should use PHPMailer. So when I started the Docker compose stack for the first time, before I did anything else, I logged into the app container and enabled the addon:

```
alberto@hetzner-vps-1:~/friendica$ docker exec -it friendica /bin/bash
root@c44798a4cf63:/var/www/html# bin/console addon enable phpmailer
Friendica[128]: console [DEBUG]: Addon phpmailer: install {"action":"install","addon":"phpmailer"} - {"file":"Addon.php","line":153,"function":"install","request-id":"67aec72353fe9","stack":"SyslogLogger::formatLog (122), SyslogLogger::addEntry (184), Addon::install (168), Addon::enable (94), Addon::doExecute (108), Console::execute (151), Console::doExecute (108), Console::execute (33)","uid":"0575b5"}
root@c44798a4cf63:/var/www/html# 
```

- Furthermore, I created a phpmailer.config.php and placed it in the config directory:

```
<?php
return [
        'phpmailer' => [
                'smtp' => true,
                'smtp_server' => 'smtp.fastmail.com',
                'smtp_port' => 587,
                'smtp_secure' => 'tls',
                'smtp_port_s' => 465,
                'smtp_username' => 'alberto@albertoventurini.com',
                'smtp_password' => '<redacted>',
                'smtp_from' => '',
        ],
];
```

- Finally, I restarted the Docker compose stack. Then I accessed the admin signup page and filled out the form. But the email is not sent. I  only get an empty Friendica page as response. Also, I don't see any errors in the logs.

I've repeated the above steps several times, without success. What could I do to further troubleshoot this issue?

Here's my `docker-compose.yml` file:

```
services:

  db:
    image: mariadb
    restart: always
    volumes:
      - ./friendica-db:/var/lib/mysql/
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    env_file:
      - db.env
    networks:
      - friendica-net

  app:
    image: friendica:fpm
    container_name: friendica
    restart: always
    volumes:
      - ./friendica-data:/var/www/html
    environment:
      - FRIENDICA_ADMIN_MAIL=alberto@albertoventurini.com
      - FRIENDICA_TZ=Africa/Johannesburg
      - FRIENDICA_LANG=en
      - FRIENDICA_URL=https://friendica.albertoventurini.com
      - FRIENDICA_SITENAME="Alberto's Friendica instance"
      - FRIENDICA_LOGGER=syslog
      - FRIENDICA_DEBUGGING=true
      - FRIENDICA_LOGLEVEL=debug
      - SMTP=smtp.fastmail.com
      - SMTP_DOMAIN=albertoventurini.com
      - SMTP_TLS=true
      - SMTP_STARTTLS=true
      - SMTP_AUTH_USER=alberto@albertoventurini.com
      - SMTP_AUTH_PASS=<redacted>
    env_file:
      - db.env
    depends_on:
      - db
    networks:
      - friendica-net

  cron:
    image: friendica:fpm
    restart: always
    volumes:
      - ./friendica-data:/var/www/html
    entrypoint: /cron.sh
    env_file:
      - db.env
    depends_on:
      - db
      - app
    networks:
      - friendica-net
    environment:
      - FRIENDICA_ADMIN_MAIL=alberto@albertoventurini.com
      - FRIENDICA_TZ=Africa/Johannesburg
      - FRIENDICA_LANG=en
      - FRIENDICA_URL=https://friendica.albertoventurini.com
      - FRIENDICA_SITENAME="Alberto's Friendica instance"
      - FRIENDICA_LOGGER=syslog
      - FRIENDICA_DEBUGGING=true
      - FRIENDICA_LOGLEVEL=debug
      - SMTP=smtp.fastmail.com
      - SMTP_DOMAIN=albertoventurini.com
      - SMTP_TLS=true
      - SMTP_STARTTLS=true
      - SMTP_AUTH_USER=alberto@albertoventurini.com
      - SMTP_AUTH_PASS=<redacted>

  web:
    image: nginx
    container_name: friendica-nginx
    restart: always
    volumes:
      - ./friendica-data:/var/www/html:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - friendica-net
      - proxied_services

networks:
  friendica-net:
  proxied_services:
    external: true
```
