### ISSUE TITLE
frio: image zoom levels on click.

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#5133]
I would love to have 3 zoom levels for images, because very often the images are very small, sometimes very long. Sometimes you can click on the images and it opens up and sometimes you can't.

So my suggestion is to open up an image on click (all the time!) and display (always with aspect ratio)

1. initial click - fit to window height/width (browser window)
2. second click - original size of the image
3. third click -  twice the size of the image (maybe configurable in settings?)

**Comment by hoergen** [comment]
A workaround is the firefox addon Imagus https://addons.mozilla.org/de/firefox/addon/imagus/

**Comment by valvin1** [comment]
I agree that at least a modal viewer for media is missing. 

On my side I've already reduced image size using stylish to avoid having to big picture in the timeline : 

```css
.wall-item-container .wall-item-content .type-link img.attachment-image,
.type-link img.attachment-image,
.type-video img.attachment-image {

    float: initial;
    margin-right: 0px;
    max-height: 250px;
    
}

.wall-item-content img {

    max-height: 250px;
    object-fit: contain;

}

```

but after doing that I miss a modal viewer which displayes image which fits to the screen size or original size.

Thank you @hoergen for the addon, it is really useful :)
