### ISSUE TITLE
2019.09-rc dbstructure dryrun is not empty

### ISSUE THREAD

**Issue by valvin1** [friendica/friendica#9189]
### Expected behavior

After upgrading bin/console dbstructure dryrun should be empty.

### Actual behavior

After upgrading I run bin/console dbstructure dryrun : 

```sql
ALTER IGNORE TABLE `intro` ADD INDEX `contact-id` (`contact-id`), ADD INDEX `uid` (`uid`), ADD FOREIGN KEY (`uid`) REFERENCES `user` (`uid`) ON UPDATE RESTRICT ON DELETE CASCADE, ADD FOREIGN KEY (`contact-id`) REFERENCES `contact` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE; 
ALTER IGNORE TABLE `participation` ADD FOREIGN KEY (`iid`) REFERENCES `item` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, ADD FOREIGN KEY (`cid`) REFERENCES `contact` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, ADD FOREIGN KEY (`fid`) REFERENCES `fcontact` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE; 
ALTER IGNORE TABLE `photo` ADD FOREIGN KEY (`contact-id`) REFERENCES `contact` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT; 
```

So I run bin/console dbstructure update. It runs without error but dryrun continues to display the same query.

I've tried playing query manually and I have this issue : 

```
MariaDB [friendica]> ALTER IGNORE TABLE `intro` ADD INDEX `contact-id` (`contact-id`), ADD INDEX `uid` (`uid`), ADD KEY (`contact-id`) REFERENCES `contact` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE; 
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'REFERENCES `contact` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE' at line 1
```

I'm not 100% this query is there since the upgrade or if it was already present.

Indexes are not yet present on table intro:

```
MariaDB [friendica]> SHOW INDEXES FROM intro\G;
*************************** 1. row ***************************
        Table: intro
   Non_unique: 0
     Key_name: PRIMARY
 Seq_in_index: 1
  Column_name: id
    Collation: A
  Cardinality: 2
     Sub_part: NULL
       Packed: NULL
         Null: 
   Index_type: BTREE
      Comment: 
Index_comment: 
1 row in set (0.001 sec)
```

I don't understand the exact error of the query?

### Friendica version you encountered the problem
2019.09-rc (2020-09-12)

### PHP version
7.3.22

### SQL version
MariaDB 10.3
